apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: nexus
  spec:
    ports:
    - name: nexus
      port: 8081
      protocol: TCP
      targetPort: 8081
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: null
    name: nexus
  subsets:
  - addresses:
    - ip: 10.1.2.1
    ports:
    - name: nexus
      port: 8081
      protocol: TCP
kind: List
metadata: {}
